Feature/blog migratie
Ordina-Group/JWorks-blog pull request #47
Opened 2024-04-18 17:27 UTC by nicholasM95

### Thank you for your contribution! Please go through this small checklist to prepare your pull request to be reviewed as soon as possible :)
* [ ] All authors were added to `_data/authors.yml` with a picture and an up-to-date bio
* [ ] The blog post image is of ratio 500x293
  * Feel free to leave a comment if you don't know how to resize your image and someone will gladly help you out
* [ ] The [**one sentence per line** method](https://raw.githubusercontent.com/brandon-rhodes/blog/master/texts/brandon/2012/one-sentence-per-line.rst) has been adopted
* [ ] A spell check has been done
* [ ] All links open in a new tab
  * Example: `[Amazing tech blog](https://ordina-jworks.github.io){:target="_blank" rel="noopener noreferrer"}`
* [ ] The post's content properly resizes according to the window's size
  * Tip: Just shorten your window's horizontal length to easily test this
  * To have images properly resize use `class="image fit"`
  * To have YouTube videos properly resize, wrap the iframe into a `<div class="responsive-video">`
* [ ] If a table of content is: check whether all links are working correctly

### Any specific remarks for the reviewers or anything you need help with?
\<enter text here>

### Checklist for the reviewers before merging
* [ ] Publishing date of the post has been correctly set
  * This can be done by renaming the filename or by setting the date in the header section of the post

2024-04-18 18:59 UTC, DenMette requested changes

2024-04-18 18:59 UTC, DenMette commented on _posts/2024-04-23-secure-blog-migration.md
> +- [Conclusion](#conclusion)
```suggestion
{:.no_toc}
- TOC
{:toc}
```

2024-04-18 18:59 UTC, DenMette commented on _posts/2024-04-23-secure-blog-migration.md
> +  * **Amazon Ip reputation List**  to block sources associated with bots or other threats.
```suggestion
  * **Known Bad Input Rules** to block requests patterns that are known to be invalid and are associated with exploitation or discovery of vulnerabilities.
  * **Amazon IP reputation List**  to block sources associated with bots or other threats.
```

2024-04-18 21:11 UTC, pietervincken requested changes
Nice post, mostly cosmetic remarks. 
The conclusion needs significant work. Make sure to stress why we/you did it: summarise intro, summarise the outcome and highlight 1 interesting thing you learned in the process.

2024-04-18 21:11 UTC, pietervincken commented on _posts/2024-04-23-secure-blog-migration.md
> +keep you safe while you're on that website. They help protect against common online
```suggestion
keep you safe while you're on a website. They help protect against common online 
```

2024-04-18 21:11 UTC, pietervincken commented on _posts/2024-04-23-secure-blog-migration.md
> +threats like hackers trying to steal your information or take control of your browser.
```suggestion
threats like hackers trying to steal your information or taking control of your browser.
```

2024-04-18 21:11 UTC, pietervincken commented on _posts/2024-04-23-secure-blog-migration.md
> +through previous project, we decided to leverage the platform for its robust security features.
```suggestion
through previous projects, we decided to leverage the platform for its robust security features.
```

2024-04-18 21:11 UTC, pietervincken commented on _posts/2024-04-23-secure-blog-migration.md
> +We've used Terraform as Infrastructure as a Code combined with GitHub Actions to deploy all our resources.
```suggestion
We used Terraform as Infrastructure as a Code combined with GitHub Actions to deploy all our resources.
```

2024-04-18 21:11 UTC, pietervincken commented on _posts/2024-04-23-secure-blog-migration.md
> +  * **Amazon Ip reputation List**  to block sources associated with bots or other threats.
```suggestion
  * **Known Bad Input Rules** to block request patterns that are known to be invalid and are associated with  exploitation or discovery of vulnerabilities.
  * **Amazon Ip reputation List**  to block sources associated with bots or other threats.
```

2024-04-18 21:11 UTC, pietervincken commented on _posts/2024-04-23-secure-blog-migration.md
> +* Created a subdomain for our blog using Route 53.
```suggestion
* We created a subdomain for our blog using Route 53. 
```

2024-04-18 21:11 UTC, pietervincken commented on _posts/2024-04-23-secure-blog-migration.md
> +* Generated a certificate via AWS ACM to ensure secure connections for our visitors.
```suggestion
* We generated a certificate via AWS ACM to ensure secure connections for our visitors. 
```

2024-04-18 21:11 UTC, pietervincken commented on _posts/2024-04-23-secure-blog-migration.md
> +* Initiated configuration of the origin, directing to our S3 bucket.
What is meant here? This is unclear for me.

2024-04-18 21:11 UTC, pietervincken commented on _posts/2024-04-23-secure-blog-migration.md
> +  * **Content-Security-Policy (CSP)** to protect your site from XSS attacks. By whitelisting resources of approved content, you can prevent the browser from loading malicious assets
```suggestion
  * **Content-Security-Policy (CSP)** to protect your site from XSS attacks. By whitelisting resources of approved content you can prevent the browser from loading malicious assets.
```

2024-04-18 21:11 UTC, pietervincken commented on _posts/2024-04-23-secure-blog-migration.md
> +Moreover, optimization for SEO ensures improved visibility and accessibility, strengthening.
```suggestion
Moreover, optimization for SEO ensures improved visibility and accessibility. 
```

2024-04-18 21:11 UTC, pietervincken commented on _posts/2024-04-23-secure-blog-migration.md
> +## Conclusion
AI generated? It repeats the same point multiple time. Rewrite to make it more fluent and less repetitive.

2024-04-18 21:11 UTC, pietervincken commented on _posts/2024-04-23-secure-blog-migration.md
> +Curious if your website could use some enhancements too? Don't wait; take the first step and conduct a scan yourself on [Security Headers](https://securityheaders.com/){:target="_blank" rel="noopener
Excellent call to action! 👍

2024-04-18 21:31 UTC, ferrevangenechten1 commented on _posts/2024-04-23-secure-blog-migration.md
> +* Initiated configuration of the origin, directing to our S3 bucket.
The origins settings of CloudFront. 
![image](https://github.com/Ordina-Group/JWorks-blog/assets/112859645/5d7cd6c6-fb49-41c1-a905-957a295af759)

But if it's already unclear for you, Il'll change it

2024-04-19 12:40 UTC, yolanv approved these changes
Fantastische blogpost mannen. Chapeau. Heel goed werk 👍

2024-04-19 12:52 UTC, pietervincken approved these changes

2024-04-23 09:21 UTC, merged